/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Analytics;

import Business.EcoSystem;
import Business.Scene.Scene;
import Business.Scene.SceneDirectory;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author shash
 */
public class AnalyticsViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AnalyticsViewJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    SceneDirectory sceneDirectory;

    public AnalyticsViewJPanel(JPanel userProcessContainer, SceneDirectory sd, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.sceneDirectory = sd;
        populateBarGraph();
    }

    public void populateBarGraph() {
        int a = 0;
        int b = 0;
        int c = 0;
        for (Scene scene : sceneDirectory.getSceneList()) {
            if (Integer.parseInt(scene.getArea_affected()) < 3000) {
                a++;
            } else if (Integer.parseInt(scene.getArea_affected()) >= 3000 && (Integer.parseInt(scene.getArea_affected()) <= 4000)) {
                b++;
            } else if (Integer.parseInt(scene.getArea_affected()) >= 4000) {
                c++;
            }
        }

        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(a, "", "<3000");
        dataset.setValue(b, "", "3000-4000");
        dataset.setValue(c, "", ">4000");
   
        JFreeChart barChart = ChartFactory.createBarChart(
                "Scenes Affected Vs Area",
                "Area",
                "No of Scenes Affected",
                dataset,
                PlotOrientation.VERTICAL,
                true, true, true);

        ChartPanel chartPanel = new ChartPanel(barChart);
        jPanel1.removeAll();
        jPanel1.add(chartPanel, BorderLayout.CENTER);
        jPanel1.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jLabel1.setText("View Analytics for Government");

        jPanel1.setBackground(new java.awt.Color(255, 51, 153));
        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
