/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Reporting_Agency_AdminPanel;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Position;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Scene.Scene;
import Business.UserAccount.UserAccount;
import UI_GoogleMap.Scene_Location;
import Validations.Validator;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author purva
 */
public class ReportingAgency_Scene_ManagementPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSitesJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Organization organization;
    UserAccount account;
    Network network;
    private Position position;

    ReportingAgency_Scene_ManagementPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.organization = organization;
        this.account = account; //To change body of generated methods, choose Tools | Templates.
        populateSiteTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSite = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblwelcome = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSiteName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNumberOfVictims = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAffectedArea = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEstimatedLoss = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        latLongTextField = new javax.swing.JTextField();
        locationBtn = new javax.swing.JButton();
        txt1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 102, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setForeground(new java.awt.Color(0, 102, 255));

        tblSite.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Scene Name", "Scene ID", "Affected Area", "Estimated Loss", "Number of Victimsl", "Zip Code", "Location Coordinates"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSite);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, 720, 110));

        btnNew.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnNew.setForeground(new java.awt.Color(102, 0, 102));
        btnNew.setText("Create New Scene");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        add(btnNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 150, -1));

        btnBack.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 0, 102));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, -1, -1));

        lblwelcome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblwelcome.setForeground(new java.awt.Color(0, 102, 255));
        add(lblwelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 33, 240, 20));

        btnDelete.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(102, 0, 102));
        btnDelete.setText("Delete Scene");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 130, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Create Scene");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 190, 30));

        txtSiteName.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtSiteName.setForeground(new java.awt.Color(102, 0, 102));
        txtSiteName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSiteNameFocusLost(evt);
            }
        });
        txtSiteName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSiteNameKeyPressed(evt);
            }
        });
        add(txtSiteName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 130, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Manage Scene Directory");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 20, 320, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Scene Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        txtNumberOfVictims.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtNumberOfVictims.setForeground(new java.awt.Color(102, 0, 102));
        txtNumberOfVictims.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumberOfVictimsFocusLost(evt);
            }
        });
        txtNumberOfVictims.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumberOfVictimsKeyPressed(evt);
            }
        });
        add(txtNumberOfVictims, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 130, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Number of  Victims");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        txtAffectedArea.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtAffectedArea.setForeground(new java.awt.Color(102, 0, 102));
        txtAffectedArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAffectedAreaKeyPressed(evt);
            }
        });
        add(txtAffectedArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 130, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 0, 102));
        jLabel6.setText("Affected Area");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        txtEstimatedLoss.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtEstimatedLoss.setForeground(new java.awt.Color(102, 0, 102));
        txtEstimatedLoss.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEstimatedLossKeyPressed(evt);
            }
        });
        add(txtEstimatedLoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 130, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 0, 102));
        jLabel7.setText("Estimated Loss");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 0, 102));
        jLabel8.setText("Zip Code");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        txtZipCode.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        txtZipCode.setForeground(new java.awt.Color(102, 0, 102));
        txtZipCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtZipCodeKeyPressed(evt);
            }
        });
        add(txtZipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 130, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Set Location");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        latLongTextField.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        latLongTextField.setForeground(new java.awt.Color(102, 0, 102));
        add(latLongTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 130, -1));

        locationBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        locationBtn.setForeground(new java.awt.Color(102, 0, 102));
        locationBtn.setText("Set Location");
        locationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationBtnActionPerformed(evt);
            }
        });
        add(locationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));
        add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 326, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/icons/imagesXODCPSFL.png"))); // NOI18N
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        if (!txtSiteName.getText().equals("")) {
            Scene s = system.getSceneList().addScene();
            s.setSceneName(txtSiteName.getText());
            s.setArea_affected(txtAffectedArea.getText());
            s.setNum_victims(Integer.parseInt(txtNumberOfVictims.getText()));
            s.setLoss_estimation(txtEstimatedLoss.getText());
            s.setZipcode(Integer.parseInt(txtZipCode.getText()));
            s.setLatLong(position);

        } else {
            JOptionPane.showMessageDialog(null, "Enter value", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        populateSiteTable();

    }//GEN-LAST:event_btnNewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblSite.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the row to delete the account", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            Scene s = (Scene) tblSite.getValueAt(selectedRow, 0);

            system.getSceneList().removeSite(s);

            JOptionPane.showMessageDialog(null, "You have successfully deleted the account");
            populateSiteTable();
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    public void populateLatLong(Position position) {
        this.position = position;
        latLongTextField.setText(position.getLatitude() + "," + position.getLongitude());
    }

    private void txtSiteNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSiteNameKeyPressed
        // TODO add your handling code here:
        //Validator.onlyString(evt, txtSiteName);
    }//GEN-LAST:event_txtSiteNameKeyPressed

    public void populateSiteTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblSite.getModel();
        dtm.setRowCount(0);
        for (Scene site : system.getSceneList().getSceneList()) {

            Object[] row = new Object[7];
            row[0] = site;
            row[1] = site.getSceneId();
            row[2] = site.getArea_affected();
            row[3] = site.getLoss_estimation();
            row[4] = site.getNum_victims();
            row[5] = site.getZipcode();
            row[6] = site.getLatLong();
            dtm.addRow(row);
        }
    }
    private void txtNumberOfVictimsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumberOfVictimsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberOfVictimsKeyPressed

    private void txtAffectedAreaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAffectedAreaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAffectedAreaKeyPressed

    private void txtEstimatedLossKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstimatedLossKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstimatedLossKeyPressed

    private void txtZipCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtZipCodeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtZipCodeKeyPressed

    private void locationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationBtnActionPerformed
        // TODO add your handling code here:
        Scene_Location muajp = new Scene_Location(userProcessContainer);
        userProcessContainer.add("Scene_Location", muajp);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_locationBtnActionPerformed

    private void txtSiteNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSiteNameFocusLost
        // TODO add your handling code here:
        if (!txtSiteName.getText().isEmpty()){

   if(!Validator.validateName(txtSiteName.getText())){

       txt1.setText("*only alphabets and spaces are allowed");

       txtSiteName.setText("");

   } else {

       txt1.setText("");

   }

}
    }//GEN-LAST:event_txtSiteNameFocusLost

    private void txtNumberOfVictimsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumberOfVictimsFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtNumberOfVictimsFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField latLongTextField;
    private javax.swing.JLabel lblwelcome;
    private javax.swing.JButton locationBtn;
    private javax.swing.JTable tblSite;
    private javax.swing.JLabel txt1;
    private javax.swing.JTextField txtAffectedArea;
    private javax.swing.JTextField txtEstimatedLoss;
    private javax.swing.JTextField txtNumberOfVictims;
    private javax.swing.JTextField txtSiteName;
    private javax.swing.JTextField txtZipCode;
    // End of variables declaration//GEN-END:variables
}
