/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_VolunatryTeam;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Position;
import Business.Network.Network;
import Business.Organization.CompanyOrganization;
import Business.Organization.HospitalOrganization;
import Business.Organization.PersonalOrganization;
import Business.Organization.NGOOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import UI_GoogleMap.Organization_Postion_Panel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nikhil
 */
public class Voluntary_OrganizationManagement extends javax.swing.JPanel {

    private OrganizationDirectory directory;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    private EcoSystem system;
    private Position position;

    /**
     * Creates new form Voluntary_OrganizationManagement
     */
    Voluntary_OrganizationManagement(JPanel userProcessContainer, OrganizationDirectory directory, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.directory = directory;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;

        populateTable();
        populateCombo();

    }

    private void populateCombo() {
        OrganizationJComboBox.removeAllItems();
        OrganizationJComboBox.addItem(Organization.Type.NGO);
        OrganizationJComboBox.addItem(Organization.Type.Hospital);
        OrganizationJComboBox.addItem(Organization.Type.Company);
        OrganizationJComboBox.addItem(Organization.Type.Personal);
    }

    public void populateLatLong(Position position) {
        this.position = position;
        latLongTextField.setText(position.getLatitude() + "," + position.getLongitude());
    }

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (organization instanceof HospitalOrganization) {
                HospitalOrganization org = (HospitalOrganization) organization;
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = org.getHospital();
                row[2] = org.getPosition();
                model.addRow(row);
            } else if (organization instanceof NGOOrganization) {
                NGOOrganization org = (NGOOrganization) organization;
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = org.getNgo();
                row[2] = org.getPosition();
                model.addRow(row);
            } else if (organization instanceof CompanyOrganization) {
                CompanyOrganization org = (CompanyOrganization) organization;
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = org.getComp();
                row[2] = org.getPosition();
                model.addRow(row);
            } else if (organization instanceof PersonalOrganization) {
                PersonalOrganization org = (PersonalOrganization) organization;
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = org.getPersonal();
                row[2] = org.getPosition();
                model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        addJButton = new javax.swing.JButton();
        OrganizationJComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        orgNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        latLongTextField = new javax.swing.JTextField();
        locationBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Org Type", "Org Name", "Org Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 53, 480, 92));

        addJButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        addJButton.setForeground(new java.awt.Color(102, 0, 102));
        addJButton.setText("ADD Organization");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });
        add(addJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        OrganizationJComboBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        OrganizationJComboBox.setForeground(new java.awt.Color(102, 0, 102));
        OrganizationJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(OrganizationJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 150, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Organization Type ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        backJButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(102, 0, 102));
        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Organization Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        orgNameTextField.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        orgNameTextField.setForeground(new java.awt.Color(102, 0, 102));
        add(orgNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 150, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Set Location");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        latLongTextField.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        latLongTextField.setForeground(new java.awt.Color(102, 0, 102));
        add(latLongTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 150, -1));

        locationBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        locationBtn.setForeground(new java.awt.Color(102, 0, 102));
        locationBtn.setText("Set Location");
        locationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationBtnActionPerformed(evt);
            }
        });
        add(locationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("ADD ORGANIZATION");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/icons/8D-Disaster_Management.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        Organization.Type type = (Organization.Type) OrganizationJComboBox.getSelectedItem();
        directory.createOrganization(type, orgNameTextField.getText(), position);
        populateTable();
    }//GEN-LAST:event_addJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void locationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationBtnActionPerformed
        // TODO add your handling code here:
        Organization_Postion_Panel muajp = new Organization_Postion_Panel(userProcessContainer);
        userProcessContainer.add("Organization_Postion_Panel", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_locationBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox OrganizationJComboBox;
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField latLongTextField;
    private javax.swing.JButton locationBtn;
    private javax.swing.JTextField orgNameTextField;
    private javax.swing.JTable organizationJTable;
    // End of variables declaration//GEN-END:variables
}
