/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_VolunatryTeam;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author nikhil
 */
public class Voluntary_WorkPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    Network network;
    UserAccount account;

    /**
     * Creates new form VoluntaryWorkAreaJPanel
     */
    public Voluntary_WorkPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.system = business;
        this.network = network;
        this.enterprise = enterprise;

        enterpriseLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageRequestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        manageOrganizationJButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Voluntary Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        userJButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        userJButton.setForeground(new java.awt.Color(102, 0, 102));
        userJButton.setText("Manage User");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 270, -1));

        manageEmployeeJButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        manageEmployeeJButton.setForeground(new java.awt.Color(102, 0, 102));
        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 270, -1));

        manageRequestJButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        manageRequestJButton.setForeground(new java.awt.Color(102, 0, 102));
        manageRequestJButton.setText("Request");
        manageRequestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRequestJButtonActionPerformed(evt);
            }
        });
        add(manageRequestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 270, -1));

        enterpriseLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(102, 0, 102));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 120, 30));

        manageOrganizationJButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        manageOrganizationJButton1.setForeground(new java.awt.Color(102, 0, 102));
        manageOrganizationJButton1.setText("Manage Organization ");
        manageOrganizationJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageOrganizationJButton1ActionPerformed(evt);
            }
        });
        add(manageOrganizationJButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 270, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/icons/imagesL4OASZEI.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        Voluntary_UserAccount_Management ramop = new Voluntary_UserAccount_Management(userProcessContainer, enterprise);
        userProcessContainer.add("Voluntary_OrganizationManagement", ramop);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed
        Voluntary_EmployeeManagement ramop = new Voluntary_EmployeeManagement(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("Voluntary_OrganizationManagement", ramop);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageRequestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRequestJButtonActionPerformed
        Voluntary_RequestPanel ramop = new Voluntary_RequestPanel(userProcessContainer, account, enterprise, network, system);
        userProcessContainer.add("Voluntary_RequestPanel", ramop);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageRequestJButtonActionPerformed

    private void manageOrganizationJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageOrganizationJButton1ActionPerformed
        // TODO add your handling code here:
        Voluntary_OrganizationManagement ramop = new Voluntary_OrganizationManagement(userProcessContainer, enterprise.getOrganizationDirectory(), enterprise, network, system);
        userProcessContainer.add("Voluntary_OrganizationManagement", ramop);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageOrganizationJButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageOrganizationJButton1;
    private javax.swing.JButton manageRequestJButton;
    private javax.swing.JButton userJButton;
    // End of variables declaration//GEN-END:variables
}
