/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_GoogleMap;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Position;
import Business.Network.Network;
import Business.Organization.CompanyOrganization;
import Business.Organization.FiresafetyOrganization;
import Business.Organization.HospitalOrganization;
import Business.Organization.PersonalOrganization;
import Business.Organization.MedicalOrganization;
import Business.Organization.NGOOrganization;
import Business.Organization.Organization;
import Business.Organization.PoliceOrganization;
import Business.Scene.Scene;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shash
 */
public class Nearest_Distance_Panel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    Organization organization;
    Network network;
    EcoSystem system;
    UserAccount account;
    Scene scene;

    Position position;

    /**
     * Creates new form Distance_Panel
     */
    public Nearest_Distance_Panel(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Scene scene, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = userAccount;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.scene = scene;
    }

    public void populateTable(String name, double distance) {
        DefaultTableModel model = (DefaultTableModel) tblDistance.getModel();

        model.setRowCount(0);
        Object[] row = new Object[2];
        row[0] = name;
        row[1] = distance;

        model.addRow(row);

      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPoliceOrg = new javax.swing.JButton();
        btnCompany = new javax.swing.JButton();
        btnHospital = new javax.swing.JButton();
        btnNGO = new javax.swing.JButton();
        btnMedicineOrg = new javax.swing.JButton();
        btnFireSafety = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDistance = new javax.swing.JTable();
        btnIndividual = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPoliceOrg.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnPoliceOrg.setForeground(new java.awt.Color(102, 0, 102));
        btnPoliceOrg.setText("Police Org Distance");
        btnPoliceOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliceOrgActionPerformed(evt);
            }
        });
        add(btnPoliceOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        btnCompany.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnCompany.setForeground(new java.awt.Color(102, 0, 102));
        btnCompany.setText("Company Org Distance");
        btnCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompanyActionPerformed(evt);
            }
        });
        add(btnCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        btnHospital.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnHospital.setForeground(new java.awt.Color(102, 0, 102));
        btnHospital.setText("Hospital Org Distance");
        btnHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalActionPerformed(evt);
            }
        });
        add(btnHospital, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        btnNGO.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnNGO.setForeground(new java.awt.Color(102, 0, 102));
        btnNGO.setText("NGO Org Distance");
        btnNGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNGOActionPerformed(evt);
            }
        });
        add(btnNGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        btnMedicineOrg.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnMedicineOrg.setForeground(new java.awt.Color(102, 0, 102));
        btnMedicineOrg.setText("Medicine Org Distance");
        btnMedicineOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicineOrgActionPerformed(evt);
            }
        });
        add(btnMedicineOrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        btnFireSafety.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnFireSafety.setForeground(new java.awt.Color(102, 0, 102));
        btnFireSafety.setText("FireSafety Org Distance");
        btnFireSafety.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFireSafetyActionPerformed(evt);
            }
        });
        add(btnFireSafety, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        tblDistance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization", "Distance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDistance);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(599, 101, 260, 343));

        btnIndividual.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnIndividual.setForeground(new java.awt.Color(102, 0, 102));
        btnIndividual.setText("Individual Volunteer Distance");
        btnIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndividualActionPerformed(evt);
            }
        });
        add(btnIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPoliceOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliceOrgActionPerformed
        // TODO add your handling code here:
        ArrayList<Organization> orgList = new ArrayList<Organization>();
        DefaultTableModel model = (DefaultTableModel) tblDistance.getModel();

        model.setRowCount(0);
        Object[] row = new Object[2];
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof PoliceOrganization) {

                    Position p1 = new Position();
                    p1.setLatitude(scene.getLatLong().getLatitude());
                    p1.setLongitude(scene.getLatLong().getLongitude());
                    p1.setName("p1");
                    if (org.populateDistance(p1) < 5) {
                        orgList.add(org);

                        row[0] = org.getName();
                        row[1] = org.populateDistance(p1);

                        model.addRow(row);
                    }
                }
            }

        }

    }//GEN-LAST:event_btnPoliceOrgActionPerformed

    private void btnMedicineOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicineOrgActionPerformed
        // TODO add your handling code here:
        ArrayList<Organization> orgList = new ArrayList<Organization>();
        DefaultTableModel model = (DefaultTableModel) tblDistance.getModel();

        model.setRowCount(0);
        Object[] row = new Object[2];
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof MedicalOrganization) {

                    Position p1 = new Position();
                    p1.setLatitude(scene.getLatLong().getLatitude());
                    p1.setLongitude(scene.getLatLong().getLongitude());
                    p1.setName("p2");
                    if (org.populateDistance(p1) < 5) {
                        orgList.add(org);

                        row[0] = org.getName();
                        row[1] = org.populateDistance(p1);

                        model.addRow(row);
                    }
                }
            }

        }
    }//GEN-LAST:event_btnMedicineOrgActionPerformed

    private void btnCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompanyActionPerformed
        // TODO add your handling code here:
        ArrayList<Organization> orgList = new ArrayList<Organization>();
        DefaultTableModel model = (DefaultTableModel) tblDistance.getModel();

        model.setRowCount(0);
        Object[] row = new Object[2];
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof CompanyOrganization) {

                    Position p1 = new Position();
                    p1.setLatitude(scene.getLatLong().getLatitude());
                    p1.setLongitude(scene.getLatLong().getLongitude());
                    p1.setName("p3");
                    if (org.populateDistance(p1) < 5) {
                        orgList.add(org);

                        row[0] = org.getName();
                        row[1] = org.populateDistance(p1);

                        model.addRow(row);
                    }
                }
            }

        }
    }//GEN-LAST:event_btnCompanyActionPerformed

    private void btnFireSafetyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFireSafetyActionPerformed
        // TODO add your handling code here:
        ArrayList<Organization> orgList = new ArrayList<Organization>();
        DefaultTableModel model = (DefaultTableModel) tblDistance.getModel();

        model.setRowCount(0);
        Object[] row = new Object[2];
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof FiresafetyOrganization) {

                    Position p1 = new Position();
                    p1.setLatitude(scene.getLatLong().getLatitude());
                    p1.setLongitude(scene.getLatLong().getLongitude());
                    p1.setName("p5");
                    if (org.populateDistance(p1) < 5) {
                        orgList.add(org);

                        row[0] = org.getName();
                        row[1] = org.populateDistance(p1);

                        model.addRow(row);
                    }
                }
            }

        }

    }//GEN-LAST:event_btnFireSafetyActionPerformed

    private void btnHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalActionPerformed
        // TODO add your handling code here:
        ArrayList<Organization> orgList = new ArrayList<Organization>();
        DefaultTableModel model = (DefaultTableModel) tblDistance.getModel();

        model.setRowCount(0);
        Object[] row = new Object[2];
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof HospitalOrganization) {

                    Position p1 = new Position();
                    p1.setLatitude(scene.getLatLong().getLatitude());
                    p1.setLongitude(scene.getLatLong().getLongitude());
                    p1.setName("p5");
                    if (org.populateDistance(p1) < 5) {
                        orgList.add(org);

                        row[0] = org.getName();
                        row[1] = org.populateDistance(p1);

                        model.addRow(row);
                    }
                }
            }

        }
    }//GEN-LAST:event_btnHospitalActionPerformed

    private void btnNGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNGOActionPerformed
        // TODO add your handling code here:
        ArrayList<Organization> orgList = new ArrayList<Organization>();
        DefaultTableModel model = (DefaultTableModel) tblDistance.getModel();

        model.setRowCount(0);
        Object[] row = new Object[2];
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof NGOOrganization) {

                    Position p1 = new Position();
                    p1.setLatitude(scene.getLatLong().getLatitude());
                    p1.setLongitude(scene.getLatLong().getLongitude());
                    p1.setName("p6");
                    if (org.populateDistance(p1) < 5) {
                        orgList.add(org);

                        row[0] = org.getName();
                        row[1] = org.populateDistance(p1);

                        model.addRow(row);
                    }
                }
            }

        }

    }//GEN-LAST:event_btnNGOActionPerformed

    private void btnIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndividualActionPerformed
        // TODO add your handling code here:
        ArrayList<Organization> orgList = new ArrayList<Organization>();
        DefaultTableModel model = (DefaultTableModel) tblDistance.getModel();

        model.setRowCount(0);
        Object[] row = new Object[2];
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            for (Organization org : ent.getOrganizationDirectory().getOrganizationList()) {
                if (org instanceof PersonalOrganization) {

                    Position p1 = new Position();
                    p1.setLatitude(scene.getLatLong().getLatitude());
                    p1.setLongitude(scene.getLatLong().getLongitude());
                    p1.setName("p7");
                    if (org.populateDistance(p1) < 5) {
                        orgList.add(org);

                        row[0] = org.getName();
                        row[1] = org.populateDistance(p1);

                        model.addRow(row);
                    }
                }
            }

        }
    }//GEN-LAST:event_btnIndividualActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompany;
    private javax.swing.JButton btnFireSafety;
    private javax.swing.JButton btnHospital;
    private javax.swing.JButton btnIndividual;
    private javax.swing.JButton btnMedicineOrg;
    private javax.swing.JButton btnNGO;
    private javax.swing.JButton btnPoliceOrg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDistance;
    // End of variables declaration//GEN-END:variables
}
