/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_GoogleMap;

import Business.Position;
import UI_ERU_Admin_WorkPanel.ERU_Manage_OrganizatonPanel;
import UI_Register.Register_Panel;
import UI_VolunatryTeam.Voluntary_OrganizationManagement;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shash
 */
public class Organization_Postion_Panel extends javax.swing.JPanel {

    /**
     * Creates new form Position_Panel
     */
    JPanel userProcessContainer;
    Browser browser;
    BrowserView view;
    Position position;

    public Organization_Postion_Panel(JPanel userProcessContainer) {
        initComponents();

        this.userProcessContainer = userProcessContainer;

        position = new Position();
        browser = new Browser();
        view = new BrowserView(browser);
        browser.loadURL("https://www.google.com/maps");

        this.mapContainer.add(view, "a");

        this.mapContainer.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        setLocationBtn = new javax.swing.JButton();
        mapContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        setLocationBtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        setLocationBtn.setForeground(new java.awt.Color(102, 0, 102));
        setLocationBtn.setText("Set Location");
        setLocationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLocationBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(setLocationBtn)
                .addContainerGap(362, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(setLocationBtn)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        mapContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(mapContainer);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void setLocationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLocationBtnActionPerformed
        // TODO add your handling code here:
        try {
            if (browser.getURL() != null) {

                System.out.println(browser.getURL());
                String[] a = browser.getURL().split("!3d", 0);
                String[] b = a[1].split("!4d");
                System.out.println("Lat" + b[0] + "  " + "Lon" + b[1]);
                double lat = Double.parseDouble(b[0]);
                double lon = Double.parseDouble(b[1]);
                position.setLatitude(lat);
                position.setLongitude(lon);
            }
            System.out.println("Lat" + position.getLatitude() + position.getLongitude());

            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            if (userProcessContainer.getComponent(componentArray.length - 1) instanceof Register_Panel) {
                Register_Panel eduRequestPanel = (Register_Panel) userProcessContainer.getComponent(componentArray.length - 1);
                eduRequestPanel.populateLatLong(position);
            } else if (userProcessContainer.getComponent(componentArray.length - 1) instanceof Voluntary_OrganizationManagement) {
                Voluntary_OrganizationManagement eduRequestPanel = (Voluntary_OrganizationManagement) userProcessContainer.getComponent(componentArray.length - 1);
                eduRequestPanel.populateLatLong(position);
            } else if (userProcessContainer.getComponent(componentArray.length - 1) instanceof ERU_Manage_OrganizatonPanel) {
                ERU_Manage_OrganizatonPanel eduRequestPanel = (ERU_Manage_OrganizatonPanel) userProcessContainer.getComponent(componentArray.length - 1);
                eduRequestPanel.populateLatLong(position);
            } else if (userProcessContainer.getComponent(componentArray.length - 1) instanceof ERU_Manage_OrganizatonPanel) {
                ERU_Manage_OrganizatonPanel eduRequestPanel = (ERU_Manage_OrganizatonPanel) userProcessContainer.getComponent(componentArray.length - 1);
                eduRequestPanel.populateLatLong(position);
            }

            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Set Position first");
        }

    }//GEN-LAST:event_setLocationBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel mapContainer;
    private javax.swing.JButton setLocationBtn;
    // End of variables declaration//GEN-END:variables
}
