/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Scene_Management;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.VoluntaryTeamER;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Resource;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shash
 */
public class Scene_Manager_ResourcePanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Enterprise enterprise;
    Network network;
    EcoSystem business;

    /**
     * Creates new form Scene_Manager_ResourcePanel
     */
    Scene_Manager_ResourcePanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.enterprise = enterprise;
        this.network = network;
        this.business = business;
        populateCombo();

    }

    private void populateCombo() {
        requestTypecombobox.removeAllItems();
        requestTypecombobox.addItem("Volunteers-Company");
        requestTypecombobox.addItem("Volunteers-Hospital");
        requestTypecombobox.addItem("Volunteers-NGO");
        requestTypecombobox.addItem("Volunteers-Personal");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        requestTypecombobox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        quantitytxt = new javax.swing.JTextField();
        requestbtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("SCENE MANAGER WORK AREA PANEL");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 350, 35));

        requestTypecombobox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        requestTypecombobox.setForeground(new java.awt.Color(102, 0, 102));
        requestTypecombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        requestTypecombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTypecomboboxActionPerformed(evt);
            }
        });
        add(requestTypecombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("REQUEST TYPE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("QUANTITY");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        quantitytxt.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        quantitytxt.setForeground(new java.awt.Color(102, 0, 102));
        quantitytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantitytxtActionPerformed(evt);
            }
        });
        add(quantitytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 60, -1));

        requestbtn.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        requestbtn.setForeground(new java.awt.Color(102, 0, 102));
        requestbtn.setText("REQUEST");
        requestbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestbtnActionPerformed(evt);
            }
        });
        add(requestbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, -1));

        btnBack.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(102, 0, 102));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/icons/untitled.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void quantitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantitytxtActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        Scene_ManagePanel manageAccountJPanel = (Scene_ManagePanel) component;
        manageAccountJPanel.populateWorkQueueTableResource();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void requestbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestbtnActionPerformed
        //  Type type = (Type) requestTypecombobox.getSelectedItem();

        Resource site = new Resource();
        site.setStatus("Requested");
        site.setSender(account);
        site.setReqType(requestTypecombobox.getSelectedItem().toString());
        site.setQty(Integer.parseInt(quantitytxt.getText()));
        site.setRemainingQty(Integer.parseInt(quantitytxt.getText()));
        account.getWorkQueue().getWorkRequestList().add(site);

        for (Network net : business.getNetworkList()) {
            for (Enterprise e : net.getEnterpriseDirectory().getEnterpriseList()) {
                if (e instanceof VoluntaryTeamER) {
                    e.getWorkQueue().getWorkRequestList().add(site);
                }
            }
        }
        JOptionPane.showMessageDialog(null, "Request Successfully Created");
    }//GEN-LAST:event_requestbtnActionPerformed

    private void requestTypecomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTypecomboboxActionPerformed

    }//GEN-LAST:event_requestTypecomboboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField quantitytxt;
    private javax.swing.JComboBox requestTypecombobox;
    private javax.swing.JButton requestbtn;
    // End of variables declaration//GEN-END:variables
}
