/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_ERU_DisasterAdmin;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DisasterOrganization;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Role.Role;
import Business.Role.SceneManager;
import Business.Scene.Scene;
import Business.Scene.SceneDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shash
 */
public class Disaster_SceneManager_Panel extends javax.swing.JPanel {

    /**
     * Creates new form DisasterSiteManagerAssignmentPanel
     */
    JPanel userProcessContainer;
    OrganizationDirectory organizationDirectory;
    Enterprise enterprise;
    Network network;
    EcoSystem system;
    DisasterOrganization disasterManagementTeamOrganization;
    SceneDirectory sceneDirectory;
    SceneManager sceneManagerRole;

    public Disaster_SceneManager_Panel(JPanel userProcessContainer, UserAccount account, DisasterOrganization disasterManagementTeamOrganization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents(); //To change body of generated methods, choose Tools | Templates.
        this.userProcessContainer = userProcessContainer;
        this.disasterManagementTeamOrganization = disasterManagementTeamOrganization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = system;
        this.sceneDirectory = new SceneDirectory();

        popSiteNameCombo();
        popSiteManagerCombo(); //To change body of generated methods, choose Tools | Templates.
        populateTable();
    }

    Disaster_SceneManager_Panel(JPanel userProcessContainer, OrganizationDirectory organizationDirectory, Enterprise enterprise, Network network, EcoSystem system) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        siteNameComboBox = new javax.swing.JComboBox();
        siteManagerComboBox = new javax.swing.JComboBox();
        btnAssign = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSiteManager = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Scene Manager Assignment");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 330, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Scene Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Scene Manager");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        siteNameComboBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        siteNameComboBox.setForeground(new java.awt.Color(102, 0, 102));
        siteNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(siteNameComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 110, -1));

        siteManagerComboBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        siteManagerComboBox.setForeground(new java.awt.Color(102, 0, 102));
        siteManagerComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(siteManagerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 110, -1));

        btnAssign.setForeground(new java.awt.Color(0, 102, 255));
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 506, -1, -1));

        jScrollPane1.setForeground(new java.awt.Color(0, 102, 255));

        tblSiteManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Site Name ", "Manager Assigned"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSiteManager);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 255, 170));

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("<<Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/icons/New Picture (6).jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, -70, 710, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        Scene scene = (Scene) siteNameComboBox.getSelectedItem();
        Employee employee = (Employee) siteManagerComboBox.getSelectedItem();
        employee.setScene(scene);
        populateTable();

    }//GEN-LAST:event_btnAssignActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void popSiteNameCombo() {
        siteNameComboBox.removeAllItems();
        for (Scene scene : system.getSceneList().getSceneList()) {
            siteNameComboBox.addItem(scene);
        }
        //}
    }

    private void popSiteManagerCombo() {
        siteManagerComboBox.removeAllItems();
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            System.out.println("asd1");
            for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                System.out.println("asd2");
                if (o instanceof DisasterOrganization) {
                    System.out.println("asd3");
                    for (UserAccount u : o.getUserAccountDirectory().getUserAccountList()) {
                        System.out.println("asd4");
                        if (u.getRole().toString().equals(Role.RoleType.SceneManager.getValue())) {
                            System.out.println("asd" + u.getEmployee().getName());
                            siteManagerComboBox.addItem(u.getEmployee());
                        }
                    }
                }
            }
        }
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblSiteManager.getModel();

        model.setRowCount(0);

        for (UserAccount u : disasterManagementTeamOrganization.getUserAccountDirectory().getUserAccountList()) {
            if (u.getRole().toString().equals(Role.RoleType.SceneManager.getValue())) {
                Object[] row = new Object[2];
                row[1] = u.getEmployee();
                row[0] = u.getEmployee().getScene();
                model.addRow(row);
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox siteManagerComboBox;
    private javax.swing.JComboBox siteNameComboBox;
    private javax.swing.JTable tblSiteManager;
    // End of variables declaration//GEN-END:variables
}
