/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_ERU_DisasterAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DisasterOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author purva
 */
public class Disaster_Admin_WorkPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisasterAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    DisasterOrganization disasterManagementTeamOrganization;
    Network network;
    EcoSystem system;
    UserAccount account;
    Organization organization;

    public Disaster_Admin_WorkPanel(JPanel userProcessContainer, UserAccount account, DisasterOrganization disasterManagementTeamOrganization, Enterprise enterprise, Network network, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.disasterManagementTeamOrganization = disasterManagementTeamOrganization;
        this.network = network;
        this.system = system;
        this.account = account;//To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userJButton = new javax.swing.JButton();
        manageEmployeeJButton = new javax.swing.JButton();
        manageSiteAdminJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Work Area - Disaster Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 350, -1));

        userJButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        userJButton.setForeground(new java.awt.Color(102, 0, 102));
        userJButton.setText("Manage User");
        userJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userJButtonActionPerformed(evt);
            }
        });
        add(userJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 200, -1));

        manageEmployeeJButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        manageEmployeeJButton.setForeground(new java.awt.Color(102, 0, 102));
        manageEmployeeJButton.setText("Manage Employee");
        manageEmployeeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEmployeeJButtonActionPerformed(evt);
            }
        });
        add(manageEmployeeJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 200, -1));

        manageSiteAdminJButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        manageSiteAdminJButton.setForeground(new java.awt.Color(102, 0, 102));
        manageSiteAdminJButton.setText("Manage Scene Assignment ");
        manageSiteAdminJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageSiteAdminJButtonActionPerformed(evt);
            }
        });
        add(manageSiteAdminJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 200, -1));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 720, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void userJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userJButtonActionPerformed
        // TODO add your handling code here:
        Disaster_User_Panel muajp = new Disaster_User_Panel(userProcessContainer, enterprise);
        userProcessContainer.add("Disaster_User_Panel", muajp);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userJButtonActionPerformed

    private void manageEmployeeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEmployeeJButtonActionPerformed

        Disaster_Employee_Panel manageEmployeeJPanel = new Disaster_Employee_Panel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("Disaster_Employee_Panel", manageEmployeeJPanel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageEmployeeJButtonActionPerformed

    private void manageSiteAdminJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageSiteAdminJButtonActionPerformed

        Disaster_SceneManager_Panel manageOrganizationJPanel = new Disaster_SceneManager_Panel(userProcessContainer, account,disasterManagementTeamOrganization,enterprise,network,system);
       userProcessContainer.add("Disaster_SceneManager_Panel", manageOrganizationJPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.next(userProcessContainer);
    }//GEN-LAST:event_manageSiteAdminJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manageEmployeeJButton;
    private javax.swing.JButton manageSiteAdminJButton;
    private javax.swing.JButton userJButton;
    // End of variables declaration//GEN-END:variables
}
